### ISSUE TITLE
Report profile with love

### ISSUE THREAD

**Issue by ishto7** [E011011101001/Twitter-Block-With-Love#10]
Hey there! 
Nice job really. I've been using this for months and can't imagine how could I have been using Twitter without this extension.
I use this extension to block retweeters of a tweet that I'm sure has been promoted by spambots. But I think sometimes it's not enough to only block them. I need to report them too to help the community. We need to keep Twitter a safe place. You have come a long way with this project and have the ability to make it even better.
So all I mean is another button to report all the profiles retweeted a tweet along with block and mute options we have already.
Many thanks,
Iman

**Comment by E011011101001** [comment]
Thanks for your idea.
However, I'm worrying that this function, if implemented, is likely to be misused deliberately by users who disagree with some Tweets. If users could easily report hundreds of real accounts as spambots at the cost of only one click, more users might feel hurt when they found their accounts frozen or locked.
I was once a victim of false spam reports, which made me upset for a long time. So I'm sorry that perhaps I will not implement it for now.
Anyway, I'm glad to hear that the userscript is helpful. You can contact me anytime you have any other needs or suggestions.
