### ISSUE TITLE
Program dosn't block anymore

### ISSUE THREAD

**Issue by Xastrax** [E011011101001/Twitter-Block-With-Love#18]
Hello i tryed the Program today to block parts of the German Nazi party .... i did as written in the tutorial but after the Programmm quoted "success" i checked and not a single account was blocked

**Comment by E011011101001** [comment]
Sorry but I cannot reproduce the bug. Could you please tell me your browser, platform and your userscript manager?

**Comment by Xastrax** [comment]
Ok i wanted to record a screencapture for you now it works i guess i needet to reboot the PC after installing it
