### ISSUE TITLE
feature request: block QRT'ers from timeline

### ISSUE THREAD

**Issue by mutsurhea** [E011011101001/Twitter-Block-With-Love#19]
my For You page is FILLED with quote-re-tweets.
i have zero interest in QRT, or those who make them.
i'd like to mute every single user who pops up there [that i'm not Following] that QRTs, automatically.
muting them individually has become annoying as theres an endless amount of them.

can this be done?

**Comment by mutsurhea** [comment]
thank you for your reply.

I decided to try making my own userscript to do it.
I don't know javascript, so struggling.

rn i can't even make a manual button that mutes someone, taking that functionality out of the 3-dots menu
[this is what i have so far](https://pastebin.com/3TkHvJCa)
all it does it opens the 3-dots menu

ive nvr used an API before, dont know how to start
do i have to be using the API for this?
what do you suggest

**Comment by E011011101001** [comment]
> ive nvr used an API before, dont know how to start
> do i have to be using the API for this?
> what do you suggest

I think using the backend APIs is the best way. Maybe you can start by learning some basic things about HTTP. Perhaps [this tutorial](https://developer.mozilla.org/en-US/docs/Web/HTTP) can help.

> i heard twitter started charging for api usage, would i have to pay?

Sorry but I do not know these things as I am only a user. Maybe you can ask the Twitter Developer Platform directly.
