### ISSUE TITLE
Support Mobile Version of Twitter Web App

### ISSUE THREAD

**Issue by OverflowCat** [E011011101001/Twitter-Block-With-Love#2]
I tried to install this script on Violent Monkey on Firefox for Android. And it seems that the likers page of a tweet will not **pop-up** as it does on PC, therefore the Block All button won't show. 

Then I tried to change my User Agent by extensions on Firefox and Yandex Browser which support extensions on Android, but Twitter detected it and just refused to let me use the Desktop mode.

**Comment by E011011101001** [comment]
Sorry but I don't have the device :(
The logic about the button is just a CSS selector followed by an append. It seems that Twitter responds with the same page for both PC and mobile agents. So maybe it's still the case mentioned in #1. 
Changing the userscript manager may solve this problem. But sadly I don't know any substitutions for Violent Monkey.

**Comment by E011011101001** [comment]
#3 Fixed
