### ISSUE TITLE
共享黑名单

### ISSUE THREAD

**Issue by wodecx** [E011011101001/Twitter-Block-With-Love#20]
https://twitter.com/baby_yutong
![image](https://github.com/E011011101001/Twitter-Block-With-Love/assets/125178172/63026e7f-c04a-44b0-9e10-bece6c1afe81)

https://twitter.com/oceanyu921206
![image](https://github.com/E011011101001/Twitter-Block-With-Love/assets/125178172/dfdf9115-5da2-4335-92f6-4842ac71832e)

https://twitter.com/RidhonaF
![image](https://github.com/E011011101001/Twitter-Block-With-Love/assets/125178172/6a513059-baef-4031-8a01-5af0ed5742a5)

**Comment by E011011101001** [comment]
I am going to delete this issue since it is nothing to do with this repo.
Maybe you would like to contact [@finedtune](https://twitter.com/finedtune) directly.
