### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Nyantcha** [E011011101001/Twitter-Block-With-Love#22]
No longer working with Elon hiding likes/retweets under “post engagements”

**Comment by E011011101001** [comment]
Thanks for the information!
(Oh no...)
I'll fix this as soon as possible.

**Comment by E011011101001** [comment]
Fixed :)
You can update to the latest version and check if it's working well in your browser.

**Comment by Nyantcha** [comment]
Thank you, it works now!
