### ISSUE TITLE
Deleted on GreasysFork

### ISSUE THREAD

**Issue by Aethyx12** [E011011101001/Twitter-Block-With-Love#28]
Hello,

I've tried to download these version (https://github.com/nwxz/Twitter-Block-With-Love-2024 & https://github.com/OverflowCat/Twitter-Block-With-Love?tab=readme-ov-file) and see which one would work, but the script has been deleted on Greasy Fork, leaving with this message "The script you requested has been deleted, but here are some related scripts."...

Can something be done? Please, I used your tool everyday and it was so useful, the only working mass blocker and now... nothing works and the potential working scripts are impossible to get on Greasy Fork...

**Comment by nwxz** [comment]
Hey, i'm new on GitHub so I didn't know how to do everything.
Anyway, while waiting for the pull request, you can install manually the forked script : 
[https://raw.githubusercontent.com/nwxz/Twitter-Block-With-Love-2024/master/index.user.js](https://raw.githubusercontent.com/nwxz/Twitter-Block-With-Love-2024/master/index.user.js)

**Comment by E011011101001** [comment]
Thanks to the fix #27 by @nwxz, the script hosted on GreasyFork is now undeleted and can be accessed by the link in [README.md#Install](https://github.com/E011011101001/Twitter-Block-With-Love#install).
