### ISSUE TITLE
Where is the “block/mute” option in post engagements? 

### ISSUE THREAD

**Issue by Nyantcha** [E011011101001/Twitter-Block-With-Love#29]
I’m sorry to open yet another issue but after reinstalling the script, I don’t see an option to actually block users (see pictures)

Perhaps this is an issue on my end?
![IMG_3527](https://github.com/E011011101001/Twitter-Block-With-Love/assets/106512999/61d63692-419b-4e86-a11d-57a30c8dc442)
![IMG_3528](https://github.com/E011011101001/Twitter-Block-With-Love/assets/106512999/7c50e0bd-0bcd-4b4c-8a31-e2d24524e145)

**Comment by E011011101001** [comment]
What is the userscript manager you are using? Can you check the console and see if there's any error messages?

**Comment by Nyantcha** [comment]
I’m using this script manager for safari

https://github.com/quoid/userscripts#userscripts-safari

I can’t find an error log but I can try a different browser and see if the error appears there too

**Comment by Nyantcha** [comment]
Ok I fixed it myself and will close this issue , thank you kindly
