### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by Nyantcha** [E011011101001/Twitter-Block-With-Love#32]
Broke this script again

**Comment by E011011101001** [comment]
In version 2024.05.17, it seems that only the UI is broken, as the "Liked By" list is not cleared after blocking or muting.
However, if you reload the page, you will find those accounts blocked and not showing up.

UI will be fixed later. Maybe on Thursday this week.

**Comment by Nyantcha** [comment]
For me even if I refresh the website, “liked by” and “retweets” still show up. 

https://github.com/E011011101001/Twitter-Block-With-Love/assets/106512999/b1328e24-4a3e-4353-a63b-e6e34759fb4b

**Comment by Nyantcha** [comment]
I don’t mind the UI broken since it was still blocking after refreshing, but now it doesn’t do that at all
Even after refreshing, accounts under “likes” and “retweets” still show up

https://github.com/E011011101001/Twitter-Block-With-Love/assets/106512999/3da26148-35f3-4c90-bb9a-3af7c95e9437

**Comment by E011011101001** [comment]
I have tested on PC and the blocking function works just ok. It seems like you are using an iPhone. Although there was no planned support on iOS, could you please tell me about the userscript manager you are using? Maybe I can take a look and see if I can help.

BTW, the titles in the video seem strange to me. I suppose the page title should be "Post engagements", and the titles of the first two tabs should be "Quotes" and "Reposts". Do you have any ideas if they are related?

**Comment by Nyantcha** [comment]
Well if it’s an iOS issue then I suppose it makes sense
I’m not sure why the titles are different on iOS, I open the page by clicking on “view post engagements” like on PC
The Userscripts manager I’m using is the open source one that can be found [here on GitHub](https://github.com/quoid/userscripts)
Thank you for looking into it, but if it’s not working on iOS that’s fair

**Comment by mjc354** [comment]
I have a similar issue in the past 3 days. However, I suspect it may be related to the fact that I am still using a laptop running Windows 8.1, and an older version of Brave (1.47.186, Chromium: 109.0.5414.119), my Userscripts manager is Tampermonkey. I do plan on upgrading very soon, so it's not a big deal, but just thought you should know.

**Comment by Nyantcha** [comment]
Funny enough, the newest update fixed it on iOS

**Comment by E011011101001** [comment]
But I did not update the script after version v2024.05.17. Do you mean an update of iOS or the userscript manager?

Glad to hear it anyway :)

**Comment by Nyantcha** [comment]
How strange, there was an update for the script. I don’t know what that update was but it fixed the issue I had with it not working on iOS. The only problem that remains is the broken UI, but that’s not a huge issue
