### ISSUE TITLE
Request add Korean Language

### ISSUE THREAD

**Issue by hellojo011** [E011011101001/Twitter-Block-With-Love#5]
I added this sentence to user script. Is it possible to reflect on the source?

'ko': {
      lang_name: '한국어',
      like_list_identifier: '타임라인: 마음에 들어 함',
      like_title: '마음에 들어 함',
      retweet_list_identifier: '타임라인: 리트윗함',
      retweet_title: '리트윗함',
      btn: '<span style="font-size: small">모두 차단<span>',
      success: '모두 차단했습니다!'
      },

**Comment by E011011101001** [comment]
Thank you!
And I changed "리트윗" to "리트윗함" to mount on '.../retweets/*' pages.

**Comment by OverflowCat** [comment]
```js
kr: {
...,
block_retweets_notice: '저희는 리트윗만 하신 사용자분들을 차단 했으나 답글 트윗하신 사용자분들은 직접 차단하셔야합니다'
}
```
