### ISSUE TITLE
Add: Block all and mute all functions for Twitter list

### ISSUE THREAD

**Issue by yuanLeeMidori** [E011011101001/Twitter-Block-With-Love#7]
Hi! 
Firstly, thank you for developing this extension. I enjoy using it.

I was thinking, it would be great if we also have a button to block all the members in a list. And, I would like to work on this new feature.

Thank you!

**Comment by E011011101001** [comment]
Thanks for your idea! However, I'm not going to work on this feature very recently.
I'll appreciate your contribution. Feel free to email me if you'd like to help.

**Comment by yuanLeeMidori** [comment]
I'll send the PR while I finish the feature. Thank you for giving me this chance :) 

Cheers

**Comment by yuanLeeMidori** [comment]
@E011011101001 Hi! I emailed the address that you put on bio, but it got rejected(reason: unavailable address). Do you have another email address? Thank you!

**Comment by E011011101001** [comment]
Sounds weird. Are you sure you have spelled `eol@eolstudy.com` correctly?

**Comment by yuanLeeMidori** [comment]
I copied it from your bio. Never mind, I fix the bug that I was trying to ask you for help. I'll send the PR in a couple of minutes! Thank you.
